#################
### AUTOSTART ###
#################

exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css & 
exec-once = systemctl --user start hyprpolkitagent
exec-once = awww-daemon &
exec-once = swaync &

